### ISSUE TITLE
Wrong subtype only in --release (Dart 2.7.2)

### ISSUE THREAD

**Issue by jscholler** [robrbecker/resize_observer#2]
Hello Rob,

I got this weird issue when I build with `webdev build --release`, I get this error right at the beginning of dispatching the event:
`main.dart.js:395` Uncaught TypeError: Instance of 'minified:cm': type 'minified:cm' is not a subtype of type 'List<minified:cs>'`

When building with `webdev build --no-release` or doing `webdev serve`, this does not happen.

After blindly poking around a bit, I noticed that the error disappeared when changing:
`static void _dispatchResizes(JsArray<JsObject> entries, JsObject jsResizeObserver)` 
to
`static void _dispatchResizes(JsArray entries, JsObject jsResizeObserver)`

I don't know if this is a proper fix but it works for me :)

BTW, I get the same issue with `ResizeObserver` from the official `dart:html`

**Comment by robrbecker** [comment]
Hey, thanks for reporting this! I'll have to investigate your proposed solution but it looks like that could be all that's needed. Is there a bug filed for dart:html as well?

**Comment by robrbecker** [comment]
I did have a chance to verify this bug. It's currently a runtime type check that "goes away" if you compile with optimization level 3 (`-O3`). I'll still fix it though.

**Comment by robrbecker** [comment]
Fixed and released version 1.0.2
